name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

 #     - uses: actions/upload-artifact@v2
 #      with:
 #         path: ./wheelhouse/*.whl
          
      - uses: addnab/docker-run-action@v3
        with:
          image: adevur/centos-8:latest
          shell: bash
          run: |
            echo "first line"
            echo "second line"
